### ISSUE TITLE
[v11] partner_vat_unique 500 Internal Server error

### ISSUE THREAD

**Issue by tundraconsulting** [OCA/partner-contact#1051]
Hi,

This module show this error if you are using website module.
To reproduce it:
Try to buy some product and insert a VAT that exists in Odoo Contacts.

Below, you can see the log:

2021-01-28 09:58:30,068 6 ERROR jxxxxxxx-test-1798217 odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 832, in dispatch
    r = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/website_sale/controllers/main.py", line 647, in address
    partner_id = self._checkout_form_save(mode, post, kw)
  File "/home/odoo/src/odoo/addons/website_sale/controllers/main.py", line 552, in _checkout_form_save
    partner_id = Partner.sudo().create(checkout).id
  File "/home/odoo/src/user/partner_firstname/models/res_partner.py", line 54, in create
    return super(ResPartner, self.with_context(context)).create(vals)
  File "/home/odoo/src/odoo/odoo/addons/base/res/res_partner.py", line 539, in create
    partner = super(Partner, self).create(vals)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 237, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/src/odoo/odoo/models.py", line 3452, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3605, in _create
    self._validate_fields(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 1057, in _validate_fields
    check(self)
  File "/home/odoo/src/user/partner_vat_unique/models/res_partner.py", line 39, in _check_vat_unique
    )) % record.vat)
odoo.exceptions.ValidationError: ('El NIF ESBxxxxxxx debe de ser único por empresa. NOTE: This partner may be archived.', None)

I think that it should show a warning message on the website and not 500 error.

What do you think?

Thank you.

Victor Torralba

**Comment by pedrobaeza** [comment]
You need to create a bridge module `website_partner_vat_unique` to handle that, as you can't add such big dependency for that use case.

Closing as no issue, but uncovered case.
