### ISSUE TITLE
ValueError: Invalid field 'on_time_rate' on model 'res.partner'

### ISSUE THREAD

**Issue by JoksMadrilon** [OCA/partner-contact#1145]
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3003, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
Exception

**Comment by pedrobaeza** [comment]
And which module in this repository is involved with this error and in which version?

**Comment by JoksMadrilon** [comment]
I cannot to fix it. I've uninstalled CONTACT module but same error continues. I don't know how to solve it. this error prevents access to customer and supplier accounts

**Comment by JoksMadrilon** [comment]
V.14

**Comment by pedrobaeza** [comment]
Sorry, but this has nothing to do with this repo and it seems you have messed up your local DB. Try to ask for help in forums.
