### ISSUE TITLE
partner_firstname incompatible with contact position

### ISSUE THREAD

**Issue by smogol-st** [OCA/partner-contact#130]
installing the module disable the creation of new contact positions. It gives an integrity error on saving contact changes.
// error message from web interface
Integrity Error

The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: lastname - lastname]

// 

--- from the log file ----

2015-06-17 15:30:24,569 5462 ERROR xxxx openerp.sql_db: bad query: INSERT INTO "res_partner" ("id", "sale_warn", "purchase_warn", "notify_email", "color", "country_id", "image", "contact_id", "use_parent_address", "active", "street", "city", "tz", "opt_out", "zip", "invoice_warn", "company_id", "parent_id", "picking_warn", "supplier", "type", "email", "is_company", "function", "lang", "vat_subjected", "street2", "customer", "name", "phone", "mobile", "contact_type", "employee", "state_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_partner_id_seq'), 'no-message', 'no-message', 'always', 0, NULL, NULL, 12, false, true, 'Rechnung', NULL, 'Europe/Zurich', false, NULL, 'no-message', 1, 7381, 'no-message', false, 'invoice', NULL, false, NULL, 'de_DE', false, 'Adresse', true, 'Company 1 Rechnungs', NULL, NULL, 'standalone', false, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/odoo80/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "lastname" violates not-null constraint
DETAIL:  Failing row contains (9219, Company 1 Rechnungs, 1, null, null, 2015-06-17 15:30:24.547528, 0, null, null, null, Rechnung, null, null, null, null, null, null, 7381, f, null, null, f, null, t, null, Adresse, f, null, 2015-06-17 15:30:24.547528, t, Europe/Zurich, 1, de_DE, 1, null, null, null, invoice, f, null, null, null, null, null, always, null, f, null, null, null, null, null, null, null, f, null, 12, null, standalone, no-message, no-message, no-message, null, null, null, no-message, null, null, null, null, null, null, null).

2015-06-17 15:30:24,570 5462 ERROR xxxxxx openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo80/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo80/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo80/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo80/openerp/service/model.py", line 149, in wrapper
    raise openerp.osv.orm.except_orm(_('Integrity Error'), msg)
except_orm: ('Integrity Error', 'The operation cannot be completed, probably due to the following:\n- deletion: you may be trying to delete a record while other records still reference it\n- creation/update: a mandatory field is not correctly set\n\n[object with reference: lastname - lastname]')
## 2015-06-17 15:30:24,570 5462 INFO sensortec werkzeug: 192.168.2.112 - - [17/Jun/2015 15:30:24] "POST /web/dataset/call_kw/res.partner/write HTTP/1.1" 200 -

Hope this will help

Regards

**Comment by NL66278** [comment]
If this error occurs on supported versions of Odoo, please re-open issue.
