### ISSUE TITLE
[10.0][FIX] requirement email_validator in partner_email_check >= 1.3 fail

### ISSUE THREAD

**Issue by igallart** [OCA/partner-contact#1358]
Hello, a new release is out of email-validator, 1.3 (https://pypi.org/project/email-validator/)
This not work in partner_email_check. With email_validator< 1.3 it works.

I don't know if odoo < 10 also.

**Comment by igallart** [comment]
/usr/local/lib/python2.7/site-packages/gevent/builtins.py:93: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  result = _import(*args, **kwargs)
2022-10-06 15:10:16,590 21 WARNING ? odoo.addons.base_geoengine.geo_helper.geo_convertion_helper: Shapely or geojson are not available in the sys path
2022-10-06 15:10:16,590 21 WARNING ? odoo.addons.base_geoengine.fields: Shapely or geojson are not available in the sys path
2022-10-06 15:10:16,593 21 WARNING ? odoo.addons.base_geoengine_demo.models.retail_machine: geojson is not available in the sys path
2022-10-06 15:10:16,864 21 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/src/core/odoo/service/wsgi_server.py", line 184, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/src/core/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/src/core/odoo/http.py", line 1325, in __call__
    self.load_addons()
  File "/opt/odoo/src/core/odoo/http.py", line 1346, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/opt/odoo/src/core/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/opt/odoo/src/partner-contact/partner_email_check/__init__.py", line 5, in <module>
    from . import models
  File "/opt/odoo/src/partner-contact/partner_email_check/models/__init__.py", line 6, in <module>
    from . import res_partner
  File "/opt/odoo/src/partner-contact/partner_email_check/models/res_partner.py", line 13, in <module>
    from email_validator import (
File "/opt/odoo/.local/lib/python2.7/site-packages/email_validator/__init__.py", line 255
    def caching_resolver(*, timeout=None, cache=None):
                          ^
SyntaxError: invalid syntax

**Comment by igallart** [comment]
Closed due to inactivity.
