### ISSUE TITLE
Bug Odoo Online v16

### ISSUE THREAD

**Issue by ghost** [OCA/partner-contact#1540]
Hello, 

I tried to install the Partner First Name module in my client Odoo v16 saas. During the upload of the zip file I had an error and now I cannot either unistall, install, upgrade or anything the module. When I try to do anything (install, unistall), nothing happens. I cannot access the database parameters. I always get this message: 

OwlError: The following error occurred in onWillStart: "Missing field string information for the field 'partner_names_order' from the 'res.config.settings' model"
    at wrapError (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:1599:77)
    at onWillStart (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:1605:117)
    at View.setup (https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:5622:202)
    at new ComponentNode (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:1560:202)
    at https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:2087:6
    at ControllerComponent.template (eval at compile (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:2052:370), <anonymous>:11:27)
    at Fiber._render (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:1498:96)
    at Fiber.render (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:1497:6)
    at ComponentNode.initiateRender (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:1565:47)

Caused by: Error: Missing field string information for the field 'partner_names_order' from the 'res.config.settings' model
    at https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6803:258
    at traverse (https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6798:203)
    at https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6798:245
    at Function.each (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:180:149)
    at traverse (https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6798:214)
    at https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6798:245
    at Function.each (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:180:149)
    at traverse (https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6798:214)
    at https://xdigit.odoo.com/web/assets/693-4f771c3/web.assets_backend.min.js:6798:245
    at Function.each (https://xdigit.odoo.com/web/assets/692-407fe4d/web.assets_common.min.js:180:149)

Has someone an idea ? What can I do to unlock the situation ?
Many thanks !

**Comment by pedrobaeza** [comment]
You can't import any business logic module in Odoo online. Such option is just for data modules (like website themes).

Closing as no real issue.
