### ISSUE TITLE
[14.0] base_location_nuts: CI is failing

### ISSUE THREAD

**Issue by fernandahf** [OCA/partner-contact#1557]
Currently, CI in version 14.0 is failing because of this error:

```
2023-06-14 18:12:34,649 251 INFO odoo odoo.addons.base_location_nuts.wizard.nuts_import: Download successfully 183248 bytes 
2023-06-14 18:12:34,657 251 INFO odoo unittest.suite: ====================================================================== 
2023-06-14 18:12:34,657 251 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.base_location_nuts.tests.test_base_location_nuts.TestBaseLocationNuts)
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 173, in _handleClassSetUp
    setUpClass()
  File "/__w/partner-contact/partner-contact/base_location_nuts/tests/test_base_location_nuts.py", line 13, in setUpClass
    cls.importer.run_import()  # loads nuts
  File "/__w/partner-contact/partner-contact/base_location_nuts/wizard/nuts_import.py", line 213, in run_import
    xmlcontent = self._download_nuts()
  File "/__w/partner-contact/partner-contact/base_location_nuts/wizard/nuts_import.py", line 154, in _download_nuts
    raise UserError(_("Downloaded file is not a valid XML file"))
odoo.exceptions.UserError: Downloaded file is not a valid XML file
```

https://github.com/OCA/partner-contact/actions/runs/5270637894/job/14266154719#step:8:450

## Module
base_location_nuts

## Describe the bug
CI failing because of an error processing a file.

## To Reproduce
14.0

**Expected behavior**
No error in CI

**Comment by LoisRForgeFlow** [comment]
This issue is affecting all open PRs in v14 and v15 right now.

**Comment by pedrobaeza** [comment]
It seems the file is no longer there. We should find a replacement. You can disable for now the tests (although the module is also not working on the initial import) for not blocking.

**Comment by rafaelbn** [comment]
Solved @LoisRForgeFlow ?

**Comment by ypapouin** [comment]
Any idea why this issue is still there for https://github.com/OCA/crm/pull/491 ?
https://github.com/OCA/crm/actions/runs/5939004985/job/16104557807?pr=491#step:8:111

Is that normal that [oca_dependencies.txt](https://github.com/OCA/crm/blob/14.0/oca_dependencies.txt) for 14.0 does not include `partner-contact` when [crm_location_nuts](https://github.com/OCA/crm/tree/14.0/crm_location_nuts) depends on `base_location_nuts` ?

**Comment by LoisRForgeFlow** [comment]
> Any idea why this issue is still there for [OCA/crm#491](https://github.com/OCA/crm/pull/491) ? https://github.com/OCA/crm/actions/runs/5939004985/job/16104557807?pr=491#step:8:111
> 
> Is that normal that [oca_dependencies.txt](https://github.com/OCA/crm/blob/14.0/oca_dependencies.txt) for 14.0 does not include `partner-contact` when [crm_location_nuts](https://github.com/OCA/crm/tree/14.0/crm_location_nuts) depends on `base_location_nuts` ?

oca_dependencies.txt are deprecated with the newer oca-ci, in which dependencies from other repos are fetched from pip.

**Comment by ypapouin** [comment]
Thank you, indeed I can now  see that a wheel is downloaded.

Looking at the exception, the issue comes from the fact that `crm_location_nuts` re-use the test class from `base_location_nuts`.
I'm preparing a PR to disable the test.
