### ISSUE TITLE
[17.0] partner_firstname: Error during Website checkout

### ISSUE THREAD

**Issue by traviswaelbro** [OCA/partner-contact#1638]
## Module
`partner_firstname`

## Describe the bug
A traceback error is raised when trying to create or update an address during the website checkout process.

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1722, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1749, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1866, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/website_sale/controllers/main.py", line 1346, in address
    'use_same': is_public_user or ('use_same' in kw and str2bool(kw.get('use_same'))),
  File "/opt/odoo/odoo/tools/misc.py", line 468, in str2bool
    raise ValueError('Use 0/1/yes/no/true/false/on/off')
ValueError: Use 0/1/yes/no/true/false/on/off
```

## To Reproduce
**Affected versions**: 17.0

Confirmed this is _cannot_ be replicated on 16.0, so it appears to be a new issue.

1. Install the `partner_firstname` and Ecommerce (`website_sale`) modules
2. Go to the website, add product to cart, and click "Checkout"
3. Click "Edit" on the address area shown
    * ![image](https://github.com/OCA/partner-contact/assets/7907616/bf45d613-5f09-45d0-9641-947ed9b7bd79)
4. Click "Add address"
    * The same happens on "Edit" of address via the website checkout form but requires manually creating an address from the backend so that it's available to test with.
5. Click "Save address"

**Expected behavior**
Checkout continues to the payment screen

**Additional context**
Replicated on runboat

**Comment by mcimam** [comment]
Can't replicate this issue. 
I think, this issue coming from website_sale module and unrelated to partner_firstname module. 
Please update to new odoo version to see if this fix your issue.
Thanks
