### ISSUE TITLE
[17.0] Error when "create and edit" customer in invoice

### ISSUE THREAD

**Issue by BertVGroenendael** [OCA/partner-contact#1757]
Module
partner_firstname

Describe the bug
When we try to create a new contact from on Invoice or Sale Order using the "create and edit" link, we get the following error:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
File "/opt/odoo/parts/odoo/odoo/odoo/http.py", line 1770, in _serve_db
return service_model.retrying(self._serve_ir_http, self.env)
File "/opt/odoo/parts/odoo/odoo/odoo/service/model.py", line 133, in retrying
result = func()
File "/opt/odoo/parts/odoo/odoo/odoo/http.py", line 1797, in _serve_ir_http
response = self.dispatcher.dispatch(rule.endpoint, args)
File "/opt/odoo/parts/odoo/odoo/odoo/http.py", line 2001, in dispatch
result = self.request.registry['ir.http']._dispatch(endpoint)
File "/opt/odoo/parts/odoo/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
response = super()._dispatch(endpoint)
File "/opt/odoo/parts/odoo/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
result = endpoint(**request.params)
File "/opt/odoo/parts/odoo/odoo/odoo/http.py", line 725, in route_wrapper
result = endpoint(self, *args, **params_ok)
File "/opt/odoo/parts/odoo/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
return self._call_kw(model, method, args, kwargs)
File "/opt/odoo/parts/odoo/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
return call_kw(request.env[model], method, args, kwargs)
File "/opt/odoo/parts/odoo/odoo/odoo/api.py", line 468, in call_kw
result = _call_kw_multi(method, model, args, kwargs)
File "/opt/odoo/parts/odoo/odoo/odoo/api.py", line 453, in _call_kw_multi
result = method(recs, *args, **kwargs)
File "/opt/odoo/parts/odoo/odoo/addons/web/models/models.py", line 994, in onchange
changed_values = {fname: initial_values.pop(fname) for fname in field_names}
File "/opt/odoo/parts/odoo/odoo/addons/web/models/models.py", line 994, in
changed_values = {fname: initial_values.pop(fname) for fname in field_names}
KeyError: 'name'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
at handleError (http://localhost:8069/web/assets/a29657c/web.assets_web.min.js:916:101)
at App.handleError (http://localhost:8069/web/assets/a29657c/web.assets_web.min.js:1542:29)
at ComponentNode.initiateRender (http://localhost:8069/web/assets/a29657c/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
at makeErrorFromResponse (http://localhost:8069/web/assets/a29657c/web.assets_web.min.js:2871:163)
at XMLHttpRequest. (http://localhost:8069/web/assets/a29657c/web.assets_web.min.js:2875:13)

To Reproduce
Affected versions: 17.0

Open a new invoice
Type a name for a new customer
press the link "Create and edit"
The error as described above will become visible

Expected behavior
The expected is that no error would occur and the that a pop-up opens with the form_view of contacts.

**Comment by denaux** [comment]
I have stumbled on the very same bug. It definitely has to do with the inheritance on the method `default_get` (res_partner.py).
```
if "firstname" in fields_list or "lastname" in fields_list:
    fields_list.append("name")
```
The problem is caused by the fact that `"name"` is already in the list `fields_list` and shouldn't be added again. The method also modifies one of its arguments in this way, I'm not sure if this is desired.

**Comment by amitgalanispeeduplight** [comment]
I had been facing the same issue in my case. I had modified the partner_firstname module method default_get(self, fields_list) like the code below, but I identified a potential issue in the default_get method. Before the changes, it looked like this and returned an error:

@api.model
def default_get(self, fields_list):
    """Invert name when getting default values."""
    if "firstname" in fields_list or "lastname" in fields_list:
            fields_list.append("name")
    result = super().default_get(fields_list)

But after I added the following condition in the code, it removed the error:

@api.model
def default_get(self, fields_list):
    """Invert name when getting default values."""
    if "firstname" in fields_list or "lastname" in fields_list:
        if "name" not in fields_list:
            fields_list.append("name")
    result = super().default_get(fields_list)
    
   You can implement the same solution in your code to fix the issue.

**Comment by rpinset** [comment]
I just found the same bug with "create and edit" on a sale order et trouver la source du problème par désintallation successive

I'm happy to find your "open issue"

![2024-06-27_23h23_22](https://github.com/OCA/partner-contact/assets/12782314/ad5d2e66-2eff-4bec-87ab-954f63ad96e4)

I try fix it for sumit a pull request
