### ISSUE TITLE
[17.0] partner_firstname : Getting error when clicking on the create and edit of the partner field from other modules

### ISSUE THREAD

**Issue by Hridhya-cybro** [OCA/partner-contact#1830]
module - partner_firstname

Issue - When clicking on create and edit of the partner fields from the sales module we get the following error:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/cybrosys/odoo-17.0/odoo/http.py", line 1764, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/cybrosys/odoo-17.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/cybrosys/odoo-17.0/odoo/http.py", line 1791, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/cybrosys/odoo-17.0/odoo/http.py", line 1995, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/cybrosys/odoo-17.0/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/cybrosys/odoo-17.0/odoo/http.py", line 741, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/cybrosys/odoo-17.0/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/cybrosys/odoo-17.0/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/cybrosys/odoo-17.0/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/cybrosys/odoo-17.0/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/cybrosys/odoo-17.0/addons/web/models/models.py", line 998, in onchange
    changed_values = {fname: initial_values.pop(fname) for fname in field_names}
  File "/home/cybrosys/odoo-17.0/addons/web/models/models.py", line 998, in <dictcomp>
    changed_values = {fname: initial_values.pop(fname) for fname in field_names}
KeyError: 'name'

The above server error caused the following client error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://localhost:8017/web/assets/3526e68/web.assets_web.min.js:916:101)
        at App.handleError (http://localhost:8017/web/assets/3526e68/web.assets_web.min.js:1543:29)
        at ComponentNode.initiateRender (http://localhost:8017/web/assets/3526e68/web.assets_web.min.js:1006:19)

Caused by: RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://localhost:8017/web/assets/3526e68/web.assets_web.min.js:2884:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8017/web/assets/3526e68/web.assets_web.min.js:2888:13)

**How to reproduce?**
Open sales or any other module, try creating a new partner from the customer field and click on the **Create and Edit** option.

Expected Behaviour
Creating and editing partners from any module should be possible as odoo's default functionality.

**Comment by mcimam** [comment]
I can't replicate this issue. Please provide more detail. 

![image](https://github.com/user-attachments/assets/5e3968f3-90ec-449f-b927-76d8e0becb57)
![image](https://github.com/user-attachments/assets/9c4a3427-5de3-4f07-b824-fcef089f7fc7)

**Comment by Hridhya-cybro** [comment]
Thank you for your support. It works fine in your latest commit.

Thanks & Regards

*Hridhya D*

Python Developer

Project & IT Department

Cybrosys Technologies

Mail

Mobile

WhatsApp

Skype

***@***.***

+91 8606827707

+91 8606827707

cybroopenerp

www.cybrosys.com
