### ISSUE TITLE
base_partner_merge error in v7

### ISSUE THREAD

**Issue by jalzaga** [OCA/partner-contact#262]
Affects version 7.0

When two customers are merged having both customer invoices, the module does the work but after that at customer invoices menu the system gives an error. 

It is due to the field account_invoice.commercial_partner_id that is not updated and keeps the old customer, that is actually deleted. 

ERROR:

Client Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1054, in search_read
    return self.do_search_read(req, model, fields, offset, limit, domain, sort)
  File "/opt/openerp/server/openerp/addons/web/controllers/main.py", line 1089, in do_search_read
    records = Model.read(ids, fields or False, req.context)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/openerp/server/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/orm.py", line 3623, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/opt/openerp/server/openerp/osv/orm.py", line 3744, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/opt/openerp/server/openerp/osv/fields.py", line 1142, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/openerp/server/openerp/osv/fields.py", line 1208, in _fnct_read
    value = value[field] or False
  File "/opt/openerp/server/openerp/osv/orm.py", line 405, in __getitem__
    field_values = self._table.read(self._cr, self._uid, ids, field_names, context=self._context, load="_classic_write")
  File "/opt/openerp/server/openerp/osv/orm.py", line 3623, in read
    result = self._read_flat(cr, user, select, fields, context, load)
  File "/opt/openerp/server/openerp/osv/orm.py", line 3744, in _read_flat
    res2 = self._columns[f].get(cr, self, ids, f, user, context=context, values=res)
  File "/opt/openerp/server/openerp/osv/fields.py", line 1142, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/openerp/server/openerp/addons/base/res/res_partner.py", line 212, in <lambda>
    _commercial_partner_id = lambda self, _args, *_kwargs: self._commercial_partner_compute(_args, *_kwargs)
  File "/opt/openerp/server/openerp/addons/base/res/res_partner.py", line 206, in _commercial_partner_compute
    while not current_partner.is_company and current_partner.parent_id:
  File "/opt/openerp/server/openerp/osv/orm.py", line 499, in __getattr__
    raise AttributeError(e)
AttributeError: 'Field is_company not found in browse_record(res.partner, 937)'

**Comment by yvaucher** [comment]
You probably need to install

https://github.com/OCA/partner-contact/tree/7.0/account_partner_merge

**Comment by jalzaga** [comment]
That´s right, this module solves the problem of commercial_partner. Thanks a lot
