### ISSUE TITLE
[8.0] [partner_create_by_vat] Odoo Server Error

### ISSUE THREAD

**Issue by sandrafig** [OCA/partner-contact#272]
I've done all the steps required to install this module, including installing python-stdnum
But when I create a new partner, click on is_company True, write the VAT number and click on "Get Vies Data", Odoo raises a server error:

_Odoo Server Error  
File "/opt/odoo/partner-contact/partner_create_by_vat/models/res_partner.py", line 26, in _get_vies_data
    result = check_vies(vat)
NameError: global name 'check_vies' is not defined_

I've tried with several VAT's and nothing seems to work, ¿what am I doing wrong?

Thank you

**Comment by feketemihai** [comment]
It depends of version of stdnum you should do a sudo pip install --upgrade stdnum

**Comment by feketemihai** [comment]
@sandrafig The version stipulated in requirements is python-stdnum==1.1, by default linux distrib have lower versions...

**Comment by sandrafig** [comment]
@feketemihai Thank you! I've removed stdnum and installed version 1.1 and now works fine.

It does work perfectly with my international partners, but it doesn't work with the spanish ones, maybe because of the specific modules of the spanish localization?

**Comment by feketemihai** [comment]
@sandrafig Can you check on VIES, http://ec.europa.eu/taxation_customs/vies/vatRequest.html?locale=en if your spanish partner is listed...or could give a vat number to check...

**Comment by sandrafig** [comment]
@feketemihai I've checked with a lot of my spanish partners and it seems they are listed but none of them has the name nor the address processed. 
I guess that has nothing to do with the module itself, so I close the issue.
Thank you

**Comment by mikemikemike77** [comment]
may be a wrong version of stdnum... i'm try to upgrade.. let you know...

**Comment by mikemikemike77** [comment]
I've upgraded the SO but still having errors:
![image](https://user-images.githubusercontent.com/18014648/38201407-7c24ac5e-3698-11e8-8e81-3a363f92a846.png)
![image](https://user-images.githubusercontent.com/18014648/38201433-8f3ba194-3698-11e8-8f4b-b18677a7cee7.png)
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-180>", line 2, in get_vies_data_from_vat
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo-10.0/addons/partner_create_by_vat/models/res_partner.py", line 63, in get_vies_data_from_vat
    res = self._get_vies_data()
  File "/opt/odoo/odoo-10.0/addons/partner_create_by_vat/models/res_partner.py", line 28, in _get_vies_data
    result = check_vies(vat)
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 144, in check_vies
    return _get_client().checkVat(number[:2], number[2:])
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 120, in _get_client
    if not _vies_client:
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 307, in __getattr__
    return getattr(port, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 421, in __getattr__
    return getattr(m, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 520, in __getattr__
    return self[name]
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 535, in __getitem__
    raise MethodNotFound, qn
MethodNotFound: Method not found: 'checkVatService.checkVatPort.__nonzero__'
