### ISSUE TITLE
[9.0] [partner_external_map] installation error Expected singleton: res.users

### ISSUE THREAD

**Issue by LionelBLANCHET** [OCA/partner-contact#313]
I have an error "Expected singleton: res.users"  when installing module partner_external_map  on odoo 9.
Is there a way to solve ?

The complete traceback is :

```
Traceback (most recent call last):
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/http.py", line 609, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/http.py", line 646, in dispatch
    result = self._call_function(**self.params)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/http.py", line 897, in __call__
    return self.method(*args, **kw)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/http.py", line 475, in response_wrap
    response = f(*args, **kw)
  File "/home/comptoirdeslustres_recette/odoo/odoo_addons_community/linked_entreprise/web/controllers/main.py", line 916, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/comptoirdeslustres_recette/odoo/odoo_addons_community/linked_entreprise/web/controllers/main.py", line 904, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/modules/loading.py", line 173, in load_module_graph
    getattr(py_module, post_init)(cr, registry)
  File "/home/comptoirdeslustres_recette/odoo/odoo_addons_community/linked/partner_external_map/hooks.py", line 26, in set_default_map_settings
    user_model._default_route_map_website().id),
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/comptoirdeslustres_recette/odoo/odoo_addons/auguria_pos_cashier_ean13/models/res_users.py", line 49, in write
    if not self.barcode:
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/fields.py", line 819, in __get__
    record.ensure_one()
  File "/home/comptoirdeslustres_recette/odoo/odoo/openerp/models.py", line 5415, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: res.users(7, 1, 32, 71, 74, 50, 58, 76, 17, 21, 53, 46, 54, 29, 55, 5, 48, 35, 6, 75, 9, 20, 87, 56, 12, 67, 84, 23, 26, 43, 15, 18, 36, 61, 14, 66, 68, 44, 27, 72, 59, 42, 57, 16, 49, 52, 10, 78, 11, 40, 91, 41, 39, 89, 38, 77, 63, 85, 86, 70, 33, 24, 34, 69, 19, 31, 3, 47, 51, 37, 60, 62, 13, 90, 64, 22, 45, 65, 88, 28, 8, 30, 4, 25)
```

**Comment by pedrobaeza** [comment]
That's because of your module auguria_pos_cashier_ean13 that is not multi record aware.
