### ISSUE TITLE
dont work in 10

### ISSUE THREAD

**Issue by cesarsc79** [OCA/partner-contact#469]
Hi

when i push    GET VIES DATA into a create a new partner................

????????????????????????????

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-263>", line 2, in get_vies_data_from_vat
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/partner-contact-10.0/partner_create_by_vat/models/res_partner.py", line 63, in get_vies_data_from_vat
    res = self._get_vies_data()
  File "/home/odoo/partner-contact-10.0/partner_create_by_vat/models/res_partner.py", line 28, in _get_vies_data
    result = check_vies(vat)
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 144, in check_vies
    return _get_client().checkVat(number[:2], number[2:])
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 120, in _get_client
    if not _vies_client:
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 307, in __getattr__
    return getattr(port, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 421, in __getattr__
    return getattr(m, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 520, in __getattr__
    return self[name]
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 535, in __getitem__
    raise MethodNotFound, qn
MethodNotFound: Method not found: 'checkVatService.checkVatPort.__nonzero__'

**Comment by pedrobaeza** [comment]
Incorrect python library version. Please update.

**Comment by cesarsc79** [comment]
Thank you Pedro

what library?

root@ubuntu:/home/odoo/partner-contact-10.0/partner_create_by_vat/tests# pip list --outdate
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
Babel (1.3) - Latest: 2.5.0 [wheel]
beautifulsoup4 (4.4.1) - Latest: 4.6.0 [wheel]
chardet (2.3.0) - Latest: 3.0.4 [wheel]
cryptography (1.2.3) - Latest: 2.0.3 [wheel]
decorator (4.0.6) - Latest: 4.1.2 [wheel]
docutils (0.12) - Latest: 0.14 [wheel]
enum34 (1.1.2) - Latest: 1.1.6 [wheel]
feedparser (5.1.3) - Latest: 5.2.1 [sdist]
funcsigs (0.4) - Latest: 1.0.2 [wheel]
gevent (1.1.0) - Latest: 1.2.2 [wheel]
greenlet (0.4.9) - Latest: 0.4.12 [wheel]
html5lib (0.999) - Latest: 0.999999999 [wheel]
idna (2.0) - Latest: 2.6 [wheel]
ipaddress (1.0.16) - Latest: 1.0.18 [wheel]
Jinja2 (2.8) - Latest: 2.9.6 [wheel]
lxml (3.5.0) - Latest: 3.8.0 [wheel]
Mako (1.0.3) - Latest: 1.0.7 [sdist]
MarkupSafe (0.23) - Latest: 1.0 [sdist]
mock (1.3.0) - Latest: 2.0.0 [wheel]
ndg-httpsclient (0.4.0) - Latest: 0.4.3 [wheel]
passlib (1.6.5) - Latest: 1.7.1 [wheel]
pbr (1.8.0) - Latest: 3.1.1 [wheel]
Pillow (3.1.2) - Latest: 4.2.1 [wheel]
psutil (3.4.2) - Latest: 5.3.0 [sdist]
psycopg2 (2.6.1) - Latest: 2.7.3.1 [wheel]
pyasn1 (0.1.9) - Latest: 0.3.4 [wheel]
pydot (1.0.29) - Latest: 1.2.3 [sdist]
Pygments (2.1) - Latest: 2.2.0 [wheel]
pyOpenSSL (0.15.1) - Latest: 17.2.0 [wheel]
pyparsing (2.0.3) - Latest: 2.2.0 [wheel]
python-dateutil (2.4.2) - Latest: 2.6.1 [wheel]
python-ldap (2.4.22) - Latest: 2.4.43 [sdist]
python-stdnum (1.2) - Latest: 1.6 [sdist]
pytz (2014.10) - Latest: 2017.2 [wheel]
PyYAML (3.11) - Latest: 3.12 [sdist]
reportlab (3.3.0) - Latest: 3.4.0 [wheel]
requests (2.9.1) - Latest: 2.18.4 [wheel]
setuptools (20.7.0) - Latest: 36.4.0 [wheel]
urllib3 (1.13.1) - Latest: 1.22 [wheel]
vobject (0.8.1rc0) - Latest: 0.9.5 [sdist]
Werkzeug (0.10.4) - Latest: 0.12.2 [wheel]
XlsxWriter (0.7.3) - Latest: 0.9.9 [wheel]
xlwt (0.7.5) - Latest: 1.3.0 [wheel]

**Comment by pedrobaeza** [comment]
suds:

https://github.com/OCA/partner-contact/blob/10.0/partner_create_by_vat/__manifest__.py#L18

**Comment by cesarsc79** [comment]
pip install suds

but  

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-263>", line 2, in get_vies_data_from_vat
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/home/odoo/partner-contact-10.0/partner_create_by_vat/models/res_partner.py", line 63, in get_vies_data_from_vat
    res = self._get_vies_data()
  File "/home/odoo/partner-contact-10.0/partner_create_by_vat/models/res_partner.py", line 28, in _get_vies_data
    result = check_vies(vat)
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 144, in check_vies
    return _get_client().checkVat(number[:2], number[2:])
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 120, in _get_client
    if not _vies_client:
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 307, in __getattr__
    return getattr(port, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 421, in __getattr__
    return getattr(m, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 520, in __getattr__
    return self[name]
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 535, in __getitem__
    raise MethodNotFound, qn
MethodNotFound: Method not found: 'checkVatService.checkVatPort.__nonzero__'

**Comment by pedrobaeza** [comment]
Maybe @feketemihai can say.

**Comment by feketemihai** [comment]
@cesarsc79 @pedrobaeza Sorry for the late reply, was in holiday, it should work, the runbot of 10 is not  raising error, so @cesarsc79 try to upgrade stdnum with "pip install --upgrade stdnum" and try after...

**Comment by cesarsc79** [comment]
Thank you @feketemihai 

but dont work yet

>root@ubuntu:/home/odoo/partner-contact-10.0# pip install stdnum
Collecting stdnum
  Could not find a version that satisfies the requirement stdnum (from versions: )
No matching distribution found for stdnum

> root@ubuntu:/home/odoo/partner-contact-10.0# pip install --upgrade stdnum
Collecting stdnum
  Could not find a version that satisfies the requirement stdnum (from versions: )
No matching distribution found for stdnum

**Comment by feketemihai** [comment]
@cesarsc79 sorry, try with "pip install --upgrade python-stdnum"

**Comment by cesarsc79** [comment]
No module named es.nif

Is there any module called es.nif??

**Comment by feketemihai** [comment]
It should be in stdnum packages, i think it's validation of spain individuals..

**Comment by feketemihai** [comment]
es.nif: NIF (Número de Identificación Fiscal, Spanish VAT number)
