### ISSUE TITLE
odoo 11  Contacts in several partners

### ISSUE THREAD

**Issue by cesarsc79** [OCA/partner-contact#573]
i just to install the module, but dont work

i go to the new tab into contact module (aplication) / create

AND........

Error:
Uncaught Error: Unknown field parent_id in domain

http://192.168.10.207:8069/web/static/src/js/core/domain.js:67
Rastreo de error:
Error: Unknown field parent_id in domain
    at Class.compute (http://192.168.10.207:8069/web/static/src/js/core/domain.js:67:23)
    at http://192.168.10.207:8069/web/static/src/js/core/domain.js:118:38
    at Function._.every._.all (http://192.168.10.207:8069/web/static/lib/underscore/underscore.js:237:12)
    at Class.compute (http://192.168.10.207:8069/web/static/src/js/core/domain.js:117:30)
    at evalModifier (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:1881:49)
    at Class._evalModifiers (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:1890:31)
    at Class._isFieldProtected (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:3084:34)
    at Class._generateChanges (http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:2656:26)
    at http://192.168.10.207:8069/web/static/src/js/views/basic/basic_model.js:973:32
    at Object.<anonymous> (http://192.168.10.207:8069/web/static/src/js/core/concurrency.js:216:31)

i ´ve tried in runbot and the same

Error:
Uncaught Error: Unknown field parent_id in domain

http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:293
Traceback:
Error: Unknown field parent_id in domain
    at Class.compute (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:293:55)
    at http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:295:830
    at Function._.every._.all (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/476-980108a/web.assets_common.js:19:571)
    at Class.compute (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:295:780)
    at evalModifier (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1180:91)
    at Class._evalModifiers (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1183:44)
    at Class._isFieldProtected (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1238:237)
    at Class._generateChanges (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1206:358)
    at http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/482-edb1f96/web.assets_backend.js:1133:18
    at Object.<anonymous> (http://3319090-11-0-3e0925.runbot2.odoo-community.org/web/content/476-980108a/web.assets_common.js:4009:295)

?????????????????????????

**Comment by pedrobaeza** [comment]
Please try on runbot to see if you find the same error.

**Comment by cesarsc79** [comment]
Of course

before reporting it as an error, I tried it on runbot 15 hours ago

**Comment by pedrobaeza** [comment]
@njeudy you were the migrator. Can you please check?

**Comment by njeudy** [comment]
@pedrobaeza ok will check and try to correct issue

can you assign this issue to me ? (can not take issue)

**Comment by njeudy** [comment]
I create PR that prevent creating new position from contact form directly. That not in the scope of this module actually. 
I had an issue / improvment not on readme, because if we need this, we have to create a clean wizard that ask for company associated with the new position, and check if it does not exist, and create it .

thanks for reporting this issue.

**Comment by cesarsc79** [comment]
welcome
