### ISSUE TITLE
Odoo server error (Odoo 10 - partner_create_by_vat)

### ISSUE THREAD

**Issue by mikemikemike77** [OCA/partner-contact#578]
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-180>", line 2, in get_vies_data_from_vat
  File "/opt/odoo/odoo/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo-10.0/addons/partner_create_by_vat/models/res_partner.py", line 63, in get_vies_data_from_vat
    res = self._get_vies_data()
  File "/opt/odoo/odoo-10.0/addons/partner_create_by_vat/models/res_partner.py", line 28, in _get_vies_data
    result = check_vies(vat)
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 144, in check_vies
    return _get_client().checkVat(number[:2], number[2:])
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 120, in _get_client
    if not _vies_client:
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 307, in __getattr__
    return getattr(port, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 421, in __getattr__
    return getattr(m, name)
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 520, in __getattr__
    return self[name]
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 535, in __getitem__
    raise MethodNotFound, qn
MethodNotFound: Method not found: 'checkVatService.checkVatPort.__nonzero__'

**Comment by mikemikemike77** [comment]
Seems that the first time works... after that I have to restart the server to get it working an other time...

**Comment by feketemihai** [comment]
@mikemikemike77 can you please post end stdnum and suds version and i will check tomorow..

**Comment by feketemihai** [comment]
And please an example of the vat number that you try to validate and raised error.

**Comment by feketemihai** [comment]
@mikemikemike77 Can you please try upgrading stdnum package with "pip install --upgrade stdnum", i tested on runbot and everything is fine, no error and partners are fetched correctly.

**Comment by mikemikemike77** [comment]
python-stdnum is already the newest version (1.2-1).
server details:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
odoo 10.0

**Comment by mikemikemike77** [comment]
i'm using suds-0.4

**Comment by mikemikemike77** [comment]
2018-04-02 15:36:39,782 2818 ERROR robertelli1-test odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-10.0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-10.0/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-180>", line 2, in get_vies_data_from_vat
  File "/opt/odoo/odoo-10.0/odoo/api.py", line 369, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo-10.0/addons/partner_create_by_vat/models/res_partner.py", line 63, in get_vies_data_from_vat
    res = self._get_vies_data()
  File "/opt/odoo/odoo-10.0/addons/partner_create_by_vat/models/res_partner.py", line 28, in _get_vies_data
    result = check_vies(vat)
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 144, in check_vies
    return _get_client().checkVat(number[:2], number[2:])
  File "/usr/lib/python2.7/dist-packages/stdnum/eu/vat.py", line 120, in _get_client
    if not _vies_client:
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 299, in __getattr__
    return getattr(port, name)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 403, in __getattr__
    return getattr(m, name)
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 494, in __getattr__
    return self[name]
  File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 507, in __getitem__
    raise MethodNotFound, qn
MethodNotFound: Method not found: 'checkVatService.checkVatPort.__nonzero__'

**Comment by feketemihai** [comment]
@mikemikemike77 I replicate your problem on a new server with the same version of dependencies, issue is that stdnum is not at the last version, so please launch "sudo pip install --upgrade python-stdnum" and it should be updated to version 1.8.1

Please tell me if it worked for you as well.

**Comment by mikemikemike77** [comment]
THANK YOU IT WORKS WELL AFTER UPGRADING!
