### ISSUE TITLE
[12] Geonames URL ERROR 404: Not Found

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/partner-contact#826]
The [default URL for Geonames](http://download.geonames.org/export/zip/) seems to be wrong.

So, I setting _geonames.url_ to [http://download.geonames.org/export/dump/](http://download.geonames.org/export/dump/) and installing _IT.zip_ archive I get this error:

`Traceback (most recent call last):
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo12/OCB/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo12/OCB/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo12/OCB/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo12/OCB/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo12/OCB/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo12/OCB/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo12/OCB/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo12/addons-extra/partner-contact/base_location_geonames_import/wizard/geonames_import.py", line 189, in run_import
    parsed_csv = self.get_and_parse_csv()
  File "/opt/odoo/odoo12/addons-extra/partner-contact/base_location_geonames_import/wizard/geonames_import.py", line 121, in get_and_parse_csv
    url = config_url % country_code
TypeError: **not all arguments converted during string formatting**`

**Comment by pedrobaeza** [comment]
It's a temporary glitch in Geonames. It has happened before. You have to wait that they restore the files.
