### ISSUE TITLE
[12.0] Error exporting partner relation on partner_multi_relation

### ISSUE THREAD

**Issue by BT-dherreros** [OCA/partner-contact#868]
When trying to export the Partner Relations, if Relation types is included the process fails
with trace:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/openerp/repos/odoo/addons/web/controllers/main.py", line 80, in wrap
    return f(*args, **kwargs)
  File "/home/openerp/repos/odoo/addons/web/controllers/main.py", line 1505, in index
    return self.base(data, token)
  File "/home/openerp/repos/odoo/addons/web/controllers/main.py", line 1453, in base
    import_data = records.export_data(field_names, self.raw_data).get('datas',[])
  File "/home/openerp/repos/odoo/odoo/models.py", line 827, in export_data
    return {'datas': self._export_rows(fields_to_export)}
  File "/home/openerp/repos/odoo/odoo/models.py", line 804, in _export_rows
    for record, xid in self.env[model].browse(ids).__ensure_xml_id():
  File "/home/openerp/repos/odoo/odoo/models.py", line 649, in __ensure_xml_id
    % (self._name, self._table))
Exception: You can not export the column ID of model res.partner.relation.type.selection, because the table res_partner_relation_type_selection is not an ordinary table.

**Comment by pedrobaeza** [comment]
The error seems clear: you can't export that column.
