### ISSUE TITLE
[13.0] partner_multi_relation: this_partner_id Key Error

### ISSUE THREAD

**Issue by drewes** [OCA/partner-contact#877]
I'm trying to migrate the **partner_multi_relation** module to 13.0.

I get the following error in the **res.partner.relation.all** model:

```
2020-04-02 15:40:52,444 87620 WARNING odoo odoo.modules.loading: Transient module states were reset 
2020-04-02 15:40:52,445 87620 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/loading.py", line 201, in load_module_graph
    registry.setup_models(cr)
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/registry.py", line 288, in setup_models
    for path in transitive_dependencies(field):
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/registry.py", line 274, in transitive_dependencies
    for seq2 in transitive_dependencies(seq1[-1], seen + [field]):
  File "/Users/Helmut/Source/Projects/root/odoo/odoo/modules/registry.py", line 272, in transitive_dependencies
    for seq1 in dependencies[field]:
KeyError: res.partner.relation.all.this_partner_id
> /Users/Helmut/Source/Projects/root/odoo/odoo/modules/registry.py(272)transitive_dependencies()
-> for seq1 in dependencies[field]:
(Pdb)
```

Does anybody have any suggestion on where I could look to fix the error, i.e. what has changed in 13.0 that would case this error?

**Comment by NL66278** [comment]
@drewes I see you are dropped in the debugger when the error happens.

Could you post the contents of the following variables when this happens?
dependencies
seen
triggers
seq2

I will try to find out what happens. The code that was changed end of last year has to do with setting up triggers for recomputing stored fields (if I understand correctly). Check commit cfb08e87b0fa.

Honestly I find it difficult to follow how this works...

**Comment by Rad0van** [comment]
@drewes did you find out? I am trying to port the same module and temporarily (I though) I fixed this by changing `class ResPartnerRelation(models.AbstractModel)` into class `ResPartnerRelation(models.Model)`. But it behaves erratically...

**Comment by drewes** [comment]
@Rad0van I've unfortunately have not been able to spend more time on this. Sorry!

Will post results if do get round to it.

**Comment by Rad0van** [comment]
@NL66278 this happens whe trying to install the module:

```
2020-05-29 12:21:26,058 26479 INFO odoo13com odoo.modules.registry: module partner_multi_relation: creating or updating database tables 
2020-05-29 12:21:26,129 26479 ERROR odoo13com odoo.sql_db: bad query: CREATE OR REPLACE VIEW res_partner_relation_all AS
     WITH base_selection AS (SELECT
    (rel.id * 100) + 0 AS id,
    'res.partner.relation' AS res_model,
    rel.id AS res_id,
    rel.left_partner_id AS this_partner_id,
    rel.right_partner_id AS other_partner_id,
    rel.type_id,
    rel.date_start,
    rel.date_end,
    False as is_inverse
    
FROM res_partner_relation rel UNION SELECT
    (rel.id * 100) + 1 AS id,
    'res.partner.relation',
    rel.id,
    rel.right_partner_id,
    rel.left_partner_id,
    rel.type_id,
    rel.date_start,
    rel.date_end,
    True as is_inverse
    
FROM res_partner_relation rel)
 SELECT
     bas.*,
     CASE
         WHEN NOT bas.is_inverse OR typ.is_symmetric
         THEN bas.type_id * 2
         ELSE (bas.type_id * 2) + 1
     END as type_selection_id,
     (bas.date_end IS NULL OR bas.date_end >= current_date) AS active
     
 FROM base_selection bas
 JOIN res_partner_relation_type typ ON (bas.type_id = typ.id)
 
        
ERROR: relation "res_partner_relation" does not exist
LINE 13: FROM res_partner_relation rel UNION SELECT
              ^
 
2020-05-29 12:21:26,131 26479 WARNING odoo13com odoo.modules.loading: Transient module states were reset
````

Than the stacktrace that @drewes posted follows. So apparently the db table is not created for some reason. See my reply above to how I tried to fix this but it behaves stangely - values are not present in object when they are supposed to and tests fail.
