### ISSUE TITLE
[12.0] partner_vat_unique: 500 Internal Server Error if VAT already exist

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/partner-contact#933]
If you insert an existing VAT in the eCommerce checkout form, you get this error:

```
... odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File ".../odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
8<
  File ".../odoo/models.py", line 1117, in _validate_fields
    check(self)
  File ".../addons-extra/OCA/partner-contact/partner_vat_unique/models/res_partner.py", line 31, in _check_vat_unique
    "partner.") % record.vat)
odoo.exceptions.ValidationError: ('The VAT xxxxxxxxxxx already exists in another partner', None)
```

**Comment by pedrobaeza** [comment]
That's something expected, as the VAT is not unique. If you want a pretty error, you have to do a `website_partner_vat_unique` module that handles that. A PR for putting this in the known issues section of the README in `partner_vat_unique` is also appreciated meanwhile.
