### ISSUE TITLE
Installing partner_firstname breaks base odoo post_install test

### ISSUE THREAD

**Issue by amh-mw** [OCA/partner-contact#944]
```
FAIL: TestFormCreate.test_create_res_partner
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/tests/test_form_create.py", line 14, in test_create_res_partner
    partner_form.name = 'a partner'
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 1677, in __setattr__
    "can't write on readonly field {}".format(field)
AssertionError: can't write on readonly field name
```

This is easily reproducible with `docker-compose up` for the following docker-compose.yaml:
```
version: '2'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  web:
    image: odoo:13
    command:
      - odoo
      - --database=odoo
      - --init=partner_firstname
      - --test-enable
      - --test-tags=base
    depends_on:
      - db
    volumes:
      - ./oca/partner-contact:/mnt/extra-addons
```

The name field in the form becomes read-only only when `is_company=True`:
https://github.com/OCA/partner-contact/blob/13.0/partner_firstname/views/res_partner.xml#L9-L14
https://github.com/OCA/partner-contact/blob/13.0/partner_firstname/views/res_partner.xml#L40-L45
https://github.com/OCA/partner-contact/blob/13.0/partner_firstname/views/res_partner.xml#L65-L73

**Comment by amh-mw** [comment]
I feel like the most appropriate solution would be to rely on _inverse_name_after_cleaning_whitespace?
https://github.com/OCA/partner-contact/blob/13.0/partner_firstname/models/res_partner.py#L112-L122

Instead of marking the field read-only, if the user modifies name, it should recalculate first and last name. If they don't like the outcome, the user can modify first and last name and it will recalculate name.

**Comment by davejames** [comment]
I can reproduce this. It seems that travis runs odoo twice, first it initializes the database by installing crm and then it runs again and installs the modules in the repo. By doing this the post tests pass, however if you initialize a fresh database with those modules from the beginning, the post tests fail, as below:

```
odoo_1  | 2020-08-13 00:48:50,895 23 INFO tests odoo.service.server: Starting post tests 
odoo_1  | 2020-08-13 00:48:50,904 23 INFO tests odoo.modules.module: odoo.addons.base.tests.test_form_create running tests. 
odoo_1  | 2020-08-13 00:48:50,905 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_bank ... 
odoo_1  | 2020-08-13 00:48:50,960 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_company ... 
odoo_1  | 2020-08-13 00:48:51,073 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_country ... 
odoo_1  | 2020-08-13 00:48:51,101 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_group ... 
odoo_1  | 2020-08-13 00:48:51,241 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_lang ... 
odoo_1  | 2020-08-13 00:48:51,265 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_partner ... 
odoo_1  | 2020-08-13 00:48:51,363 23 INFO tests odoo.addons.base.tests.test_form_create: ====================================================================== 
odoo_1  | 2020-08-13 00:48:51,364 23 ERROR tests odoo.addons.base.tests.test_form_create: FAIL: TestFormCreate.test_create_res_partner
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/tests/test_form_create.py", line 14, in test_create_res_partner
odoo_1  |     partner_form.name = 'a partner'
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/tests/common.py", line 1677, in __setattr__
odoo_1  |     "can't write on readonly field {}".format(field)
odoo_1  | AssertionError: can't write on readonly field name
odoo_1  |  
odoo_1  | 2020-08-13 00:48:51,364 23 INFO tests odoo.addons.base.tests.test_form_create: Starting TestFormCreate.test_create_res_users ... 
```

Starting with an empty database:
Tests pass with
`odoo -d tests --test-enable --stop-after-init --workers=0 --init crm && odoo -d tests --test-enable --stop-after-init --workers=0 --init partner_firstname
`

Tests fail with
`odoo -d tests --test-enable --stop-after-init --workers=0 --init partner_firstname
`

**Comment by gurneyalex** [comment]
Reopening: this is a very real issue if you want to develop an addon on odoo.sh with a dependency on partner_firstname -> the dev branch will be red on odoo.sh's CI

**Comment by InformatiqueProg** [comment]
it would appear that this problem is still relevant

I develop an add-on on odoo.sh and I have this error 
```
25-08-27 07:08:27,818 4 INFO ...  odoo.addons.mail.tests.test_res_partner: Starting TestPartner.test_name_create_corner_cases ... 
2025-08-27 07:08:27,855 4 INFO ... odoo.addons.mail.tests.test_res_partner: ====================================================================== 
2025-08-27 07:08:27,855 4 ERROR ... odoo.addons.mail.tests.test_res_partner: ERROR: Subtest TestPartner.test_name_create_corner_cases (sample='', login='admin')
Traceback (most recent call last):
  File "<decorator-gen-125>", line 2, in test_name_create_corner_cases
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 2340, in _users
    func(*args, **kwargs)
File "/home/odoo/src/odoo/addons/mail/tests/test_res_partner.py", line 506, in test_name_create_corner_cases
    self.env['res.partner'].name_create(sample)[0]    
  ...
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/odoo/models.py", line 5289, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/odoo/models.py", line 1631, in _validate_fields
    check(self)
  File "/home/odoo/src/user/partner_firstname/models/res_partner.py", line 261, in _check_name
    raise exceptions.EmptyNamesError(record, self.env)
odoo.addons.partner_firstname.exceptions.EmptyNamesError: ("Error(s) with partner 823's name.", 'No name is set.')
```

@gurneyalex any solution or tips ?
